const WHATSAPP_NUMBER='573183310300';
const wa=(message)=>`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
const answers={
 noimage:{title:'No da imagen',text:'Puede relacionarse con pantalla, memoria, alimentación, cableado, GPU o placa. Sin abrir el equipo, podemos hacer unas comprobaciones básicas.',steps:['Comprueba brillo y cargador/alimentación.','Prueba un monitor externo si tienes uno.','Desconecta periféricos USB y prueba de nuevo.','Si enciende pero sigue sin imagen, conviene revisión técnica.']},
 slow:{title:'Equipo lento',text:'Las causas frecuentes incluyen almacenamiento saturado o degradado, poca memoria, procesos en segundo plano, temperatura o software.',steps:['Revisa cuánto espacio libre queda.','Reinicia y observa si el problema aparece desde el arranque.','Comprueba si el equipo se calienta más de lo habitual.','Si continúa, JE puede revisar rendimiento y hardware.']},
 power:{title:'No enciende',text:'Primero hay que diferenciar entre ausencia total de energía y un equipo que enciende pero no inicia.',steps:['Prueba otra toma eléctrica.','Revisa cargador, cable y conectores visibles.','Desconecta periféricos y prueba de nuevo.','Si no hay señales de vida, evita forzar el equipo y solicita revisión.']},
 hot:{title:'Se calienta',text:'La temperatura puede subir por polvo, ventilación obstruida, pasta térmica, ventilador o carga elevada.',steps:['No uses el equipo sobre cama o superficies que tapen ventilación.','Revisa si los ventiladores giran.','Guarda tu trabajo si presenta apagados o bloqueos.','Una limpieza y revisión térmica puede ser necesaria.']},
 battery:{title:'No carga / batería',text:'Puede ser cargador, conector, batería, circuito de carga o configuración.',steps:['Prueba el cargador y otra toma.','Observa si el equipo funciona conectado a corriente.','No fuerces conectores ni uses cargadores incompatibles.','Si falla de forma intermitente, solicita diagnóstico.']},
 internet:{title:'Internet / Wi-Fi',text:'Primero conviene separar si falla el equipo, el Wi-Fi o el servicio de Internet.',steps:['Reinicia el router y espera unos minutos.','Prueba otro dispositivo en la misma red.','Acerca el equipo al router para descartar señal.','Si otros dispositivos funcionan y este no, JE puede revisar configuración o hardware.']},
 audio:{title:'Audio',text:'Puede ser configuración, controlador, salida seleccionada, conector o hardware.',steps:['Revisa volumen y dispositivo de salida.','Prueba audífonos y los altavoces internos.','Reinicia el equipo.','Si solo falla una salida, puede requerir revisión.']},
 other:{title:'Otro problema',text:'Descríbelo con tus propias palabras en JE IA y te ayudaremos a organizar la información antes de contactar a JE.',steps:['Qué equipo es y qué modelo conoces.','Qué ocurrió justo antes de la falla.','Qué señales aparecen: luces, sonidos, mensajes.','Qué pruebas ya realizaste.']}
};
function setWhatsAppLinks(){document.querySelectorAll('[data-wa]').forEach(a=>{a.href=wa(a.dataset.wa);a.target='_blank';a.rel='noopener'})}
function addBubble(type,html){const d=document.createElement('div');d.className=`bubble ${type}`;d.innerHTML=html;document.querySelector('#chat').appendChild(d);d.scrollIntoView({behavior:'smooth',block:'end'})}
function analyze(text){const t=text.toLowerCase();let k='other';if(/no.*imagen|pantalla.*negra|sin.*imagen|no.*video/.test(t))k='noimage';else if(/lento|lenta|demora|pegado|traba/.test(t))k='slow';else if(/no.*enciende|no.*prende|muerto|no.*arranca/.test(t))k='power';else if(/calienta|caliente|temperatura|sobrecal/.test(t))k='hot';else if(/carg|bater[ií]a|no.*carga/.test(t))k='battery';else if(/internet|wifi|wi-fi|red/.test(t))k='internet';else if(/audio|sonido|parlante|altavoz/.test(t))k='audio';return answers[k]}
const form=document.querySelector('#chatForm');form.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#problem');const text=input.value.trim();if(!text)return;addBubble('user',text.replace(/[<>&]/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[m])));const a=analyze(text);const msg=`<strong>JE IA · Orientación inicial</strong><br>${a.text}<h4>Qué puedes revisar</h4><ol>${a.steps.map(s=>`<li>${s}</li>`).join('')}</ol><a href="${wa(`Hola JE Soluciones 👋. Vengo desde JE IA. Mi problema es: "${text}". La orientación inicial fue: ${a.title}. Quiero solicitar atención.`)}" target="_blank" rel="noopener">📲 Enviar este caso a JE por WhatsApp →</a>`;setTimeout(()=>addBubble('bot',msg),250);input.value=''});
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{const a=answers[b.dataset.tool]||answers.other;const box=document.querySelector('#toolResult');box.hidden=false;box.innerHTML=`<h3>${a.title}</h3><p>${a.text}</p><ol>${a.steps.map(s=>`<li>${s}</li>`).join('')}</ol><a href="${wa(`Hola JE Soluciones 👋. Usé la herramienta de JE IA. Tengo un problema de: ${a.title}. Quiero orientación/revisión.`)}" target="_blank" rel="noopener">📲 Continuar con JE por WhatsApp →</a>`;box.scrollIntoView({behavior:'smooth',block:'center'})}));
document.querySelector('#year').textContent=new Date().getFullYear();setWhatsAppLinks();